// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetConfig():Promise<config.AppConfig>;

export function IsRunning():Promise<boolean>;

export function OpenPath(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function StartMonitoring(arg1:config.AppConfig):Promise<void>;

export function StopMonitoring():Promise<void>;
