// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartMonitoring(arg1) {
  return window['go']['main']['App']['StartMonitoring'](arg1);
}

export function StopMonitoring() {
  return window['go']['main']['App']['StopMonitoring']();
}
